import type { Booking, Expert } from './types';
import { Timestamp } from 'firebase/firestore';

const experts: Expert[] = [
  {
    id: '1',
    name: 'Dr. Evelyn Reed',
    email: 'evelyn.reed@example.com',
    profilePictureUrl: '/avatar.png',
    title: 'Licensed Psychologist',
    serviceType: 'Therapist',
    location: 'New York, NY',
    summary: 'Dr. Reed specializes in cognitive-behavioral therapy and mindfulness practices.',
    contact: {
      messaging: true,
      call: true,
      phone: '555-0101',
      whatsapp: '+15550101',
    },
    services: [{ name: 'Individual Therapy' }, { name: 'Couples Counseling' }],
    demoPhotos: [],
    experience: 15,
    languages: ['English', 'Spanish'],
    workingHours: '9 AM - 6 PM',
    availabilityDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    isOnline: true,
  },
  {
    id: '2',
    name: 'Marcus Thorne',
    email: 'marcus.thorne@example.com',
    profilePictureUrl: '/avatar.png',
    title: 'Certified Financial Planner',
    serviceType: 'Financial Planner',
    location: 'Chicago, IL',
    summary: 'Marcus helps individuals and families achieve their financial goals.',
    contact: {
      messaging: true,
      call: false,
      whatsapp: '+15550102',
    },
    services: [{ name: 'Retirement Planning' }, { name: 'Investment Management' }],
    demoPhotos: [],
    experience: 8,
    languages: ['English'],
    workingHours: '10 AM - 7 PM',
    availabilityDays: ['Monday', 'Wednesday', 'Friday'],
    isOnline: true,
  },
  {
    id: '3',
    name: 'Isabelle Chen',
    email: 'isabelle.chen@example.com',
    profilePictureUrl: '/avatar.png',
    title: 'Senior Web Developer',
    serviceType: 'Web Developer',
    location: 'San Francisco, CA',
    summary: 'Full-stack developer with expertise in React and Node.js.',
    contact: {
      messaging: true,
      call: true,
      phone: '555-0103',
      whatsapp: '+15550103',
    },
    services: [
      { name: 'Frontend Development' },
      { name: 'Backend API Development' },
      { name: 'Full Project Build' },
    ],
    demoPhotos: [],
    experience: 10,
    languages: ['English', 'Mandarin'],
    workingHours: 'Flexible',
    availabilityDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    isOnline: true,
  },
  {
    id: '4',
    name: "Liam O'Connell",
    email: 'liam.oconnell@example.com',
    profilePictureUrl: '/avatar.png',
    title: 'Master Plumber',
    serviceType: 'Plumber',
    location: 'Boston, MA',
    summary: 'Reliable plumbing solutions for homes and businesses.',
    contact: {
      messaging: false,
      call: true,
      phone: '555-0104',
    },
    services: [{ name: 'Emergency Repairs' }, { name: 'Fixture Installation' }],
    demoPhotos: [],
    experience: 20,
    languages: ['English'],
    workingHours: '24/7 for emergencies',
    availabilityDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    isOnline: true,
  },
  {
    id: '5',
    name: 'Dr. Aisha Khan',
    email: 'aisha.khan@example.com',
    profilePictureUrl: '/avatar.png',
    title: 'General Physician',
    serviceType: 'Doctor',
    location: 'Mumbai, IN',
    summary: 'Trusted physician focused on preventative care.',
    contact: {
      messaging: true,
      call: true,
      phone: '555-0105',
      whatsapp: '+915550105',
    },
    services: [{ name: 'General Consultation' }, { name: 'Annual Health Check-up' }],
    demoPhotos: [],
    experience: 12,
    languages: ['English', 'Hindi', 'Marathi'],
    workingHours: '10 AM - 1 PM, 5 PM - 8 PM',
    availabilityDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    isOnline: true,
  },
  {
    id: '6',
    name: 'Raj Patel',
    email: 'raj.patel@example.com',
    profilePictureUrl: '/avatar.png',
    title: 'Certified Electrician',
    serviceType: 'Electrician',
    location: 'Delhi, IN',
    summary: 'Licensed electrician with 10 years of experience.',
    contact: {
      messaging: false,
      call: true,
      phone: '555-0106',
    },
    services: [{ name: 'Electrical Wiring' }, { name: 'Appliance Installation' }],
    demoPhotos: [],
    experience: 10,
    languages: ['Hindi', 'English'],
    workingHours: '9 AM - 7 PM',
    availabilityDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    isOnline: true,
  },
];

// BOOKINGS (unchanged logic – already correct)
const createBooking = (
  id: string,
  expertId: string,
  userId: string,
  status: 'accepted' | 'completed' | 'cancelled' | 'pending' | 'upcoming',
  date: Date,
  partialData: Partial<Booking>
): Booking => {
  const now = Timestamp.now();
  return {
    id,
    expertId,
    userId,
    status,
    verificationCode: Math.floor(100000 + Math.random() * 900000).toString(),
    scheduledDate: Timestamp.fromDate(date),
    timeSlot: 'morning',
    createdAt: now,
    acceptedAt: status === 'accepted' || status === 'completed' ? now : null,
    startedAt: status === 'completed' ? now : null,
    completedAt: status === 'completed' ? now : null,
    userName: 'Mock User',
    expertName: 'Mock Expert',
    service: 'Mock Service',
    participantIds: [userId, expertId],
    markedCompleteAt: null,
    expiresAt: null,
    expiryType: 'today',
    ...partialData,
  };
};

const bookings: Booking[] = [];

export { experts, bookings };
